python -- libs: {style.animated: true}
python -- OOPs: {style.animated: true}
python -- Style Guide: {style.animated: true}
libs -- NumPy: {style.animated: true}
libs -- pandas: {style.animated: true}
libs -- Apache Tika: {style.animated: true}
libs -- Pillow: {style.animated: true}

Style Guide -- Ruff: {style.animated: true}

Assessing: {
  Rust
  Go
}

Challenges: {
  Advent of Code: {
    2023
  }
  hackerrank
}
python -- Challenges.Advent of Code.2023: {style.animated: true}
python -- Challenges.hackerrank: {style.animated: true}
