Jupyter -- Python: {style.animated: true}

Python -- libs: {style.animated: true}
Python -- OOPs: {style.animated: true}
Python -- Style Guide: {style.animated: true}

libs -- NumPy: {style.animated: true}
libs -- pandas: {style.animated: true}
libs -- Apache Tika: {style.animated: true}
libs -- Pillow: {style.animated: true}
libs -- "Regular expression (regex)": {style.animated: true}

Style Guide -- Ruff: {style.animated: true}

Assessing: {
  Rust
  Go
  AWS
}

Challenges: {
  Advent of Code: {
    2023
  }
  hackerrank
}

Python -- Challenges.Advent of Code.2023: {style.animated: true}
Assessing.Rust -- Challenges.Advent of Code.2023: {style.animated: true}
Python -- Challenges.hackerrank: {style.animated: true}

Linux: {
  Bash
  Zsh
}

Python Env: {
  Conda
  Pyenv
}

Python Env -- Python: {style.animated: true}
